export const Apiconfig = {
    AdminList: 'users/list',
    UserList: 'admin/users/list',
    PagesList: 'admin/pages/getlist',
    PageTranslate: 'admin/pages/translatelanguage',
    PageSettings: 'admin/pages/getPageSetting',
    PageEdit: 'admin/pages/editpage',
    PageSubmit: 'admin/pages/submitmainpage',
    PageDelete: 'admin/pages/deletepage',
    PageLanguages: 'admin/pages/getsublist',
    getSettingsData: 'admin/settings',
    saveSettingsData: 'admin/settings/save',
    saveSocialSettings: 'admin/social-networks/save',
    ContactsList: 'admin/contactus/list',
    ContactView: 'admin/contactus/view',
    ContactDelete: 'admin/contactus/delete',
    ContactReply: 'admin/contactus/reply',
    getPostHeaderList: 'admin/postheader/list',
    savePostHeader: 'admin/postheader/save',
    editPostHeader: 'admin/postheader/edit',
    deletePostHeader: 'admin/postheader/delete',
    getAppearanceList: 'admin/appearance/list',
    saveAppearance: 'admin/appearance/save',
    saveFixedHeader: 'admin/appearance/fixed-header-save',
    saveFixedAside: 'admin/appearance/fixed-aside-save',
    getCurrenciesList: 'admin/currencies/list',
    currencyedit: 'admin/currencies/edit',
    currencysave: 'admin/currencies/save',
    currencydelete: 'admin/currencies/delete',
    getUserwalletdata: 'admin/users/wallet-transaction-lists',
    getUserdata: 'admin/users/edit',
    Usersubmit: 'admin/users/save',
    UserDelete: 'admin/users/delete',
    CouponList: 'admin/coupon/list',
    CouponEdit: 'admin/coupon/edit',
    CouponSave: 'admin/coupon/save',
    CouponDelete: 'admin/coupon/delete',
    paymentlist: 'admin/paymentgateway/list',
    paymentedit: 'admin/paymentgateway/edit',
    paymentsave: 'admin/paymentgateway/save',
    paymentdelete: 'admin/paymentgateway/delete',
    smsgateedit: 'admin/smsgateway/edit',
    smsgatesave: 'admin/smsgateway/save',
    cancellist: 'admin/cancellation/list',
    canceledit: 'admin/cancellation/edit',
    cancelsave: 'admin/cancellation/save',
    canceldelete: 'admin/cancellation/delete',
    languagelist: 'admin/language/list',
    languageedit: 'admin/language/edit',
    languagesave: 'admin/language/save',
    languagedelete: 'admin/language/delete',
    languagemanagelist: 'admin/language/manage/list',
    languagemanageadd: 'admin/language/manage/add',
    languagemanagesave: 'admin/language/manage/save',
    languagemanagedelete: 'admin/language/manage/delete',
    languagemobilelist: 'admin/language/mobile/list',
    languagemobiledwnld: 'admin/language/mobile/download',
    lanuagemobilesave: 'admin/language/mobile/save',
    categorylist: 'admin/categories/list',
    categoryslug: 'admin/categories/check-category-slug',
    categoryedit: 'admin/categories/edit',
    categorysave: 'admin/categories/save',
    categorydelete: 'admin/categories/delete',
    subcategorylist: 'admin/categories/subcategory-list',
    subcategorysave: 'admin/sub-categories/save',
    categorypriority: 'admin/categories/update-priority',
    Earningslist: 'admin/earnings/list',
    templateList: 'admin/email-template/list',
    addTemplate: 'admin/email-template/save',
    editTemplate: 'admin/email-template/edit',
    deleteTemplate: 'admin/email-template/delete',
    translateLanguage: 'admin/pages/translatelanguage',
    peopleCmdList: 'admin/peoplecmd/list',
    peopleCmdEdit: 'admin/peoplecmd/edit',
    peopleCmdSave: 'admin/peoplecmd/save',
    peopleCmdDelete: 'admin/peoplecmd/delete',
    paymentPriceList: 'admin/posttask/list',
    paymentPriceSave: 'admin/posttask/save',
    paymentPriceEdit: 'admin/posttask/edit',
    paymentPriceDelete: 'admin/posttask/delete',
    reviewlist: 'admin/review/list',
    reviewdelete: 'admin/review/delete',
    reviewedit: 'admin/review/edit',
    reviewsave: 'admin/review/save',
    experiencelist: 'admin/experience/list',
    experienceedit: 'admin/experience/edit',
    experiencesave: 'admin/experience/save',
    experiencedelete: 'admin/experience/delete',
    questionlist: 'admin/question/list',
    questionedit: 'admin/question/edit',
    questionsave: 'admin/question/save',
    questiondelete: 'admin/question/delete',
    subscriberslist: 'admin/newsletter/list',
    subscriberssendmail: 'admin/newsletter/send-bulk-mail',
    subscribersmailtemplates: 'admin/email-template/getsubscripermail',
    subscribersdelete: 'admin/newsletter/delete',
    subscribersbulkmail: 'admin/newsletter/send-bulk-mail',
    defaultlang: 'admin/language/set-default',
    defaultcurrency: 'admin/currencies/set-default',
    userremove: 'admin/users/remove',
    expertslist: 'admin/taskers/list',
    taskerstatusupdate: 'admin/taskers/update-status',
    taskercatlist: 'admin/taskers/category-lists',
    taskerdocumentslist: 'admin/taskers/document-lists',
    taskersquslist: 'admin/taskers/question-lists',
    taskerexperiencelist: 'admin/taskers/experience-lists',
    taskerphonecheck: 'admin/taskers/check-phone-number',
    taskeredit: 'admin/taskers/edit',
    taskersave: 'admin/taskers/save',
    taskersdelete: 'admin/taskers/delete',
    taskersrestore: 'admin/taskers/restore',
    taskerremove: 'admin/taskers/remove',
    documentslist: 'admin/documents/list',
    documentedit: 'admin/documents/edit',
    documentsave: 'admin/documents/save',
    documentdelete: 'admin/documents/delete',
    Userrestore: 'admin/users/restore',
    Pushnotificationuserlist: 'admin/notifications/users-list',
    Pushnotificationtaskerlist: 'admin/notifications/taskers-list',
    Pushnotificationtemplatelist: 'admin/notifications/templates-list',
    Pushnotificationtemplatedelete: 'admin/notifications/delete',
    Pushnotificationtemplateedit: 'admin/notifications/edit',
    Pushnotificationtemplatesave: 'admin/notifications/save',

    Pushnotificationemailtemplates: 'admin/notifications/mail-templates',
    Pushnotificationmessagetemplates: 'admin/notifications/message-templates',
    Pushnotificationsendmessage: 'admin/notifications/send-message',
    Pushnotificationsendmail: 'admin/notifications/send-mail',
    taskerdefaultcurrency: 'admin/currencies/get-default',
    dashboardstats: 'admin/dashboard/statistics',
    dashboardearnings: 'admin/dashboard/earnings',
    dashboardstripe: 'admin/dashboard/stripe-details',
    jobList: 'admin/tasks/list',
    jobEdit: 'admin/tasks/edit',
    jobDelete: 'admin/tasks/delete',
    jobRemove: 'admin/tasks/remove',
    jobTransactionList: 'admin/tasks/transaction-lists',
    Payoutlist: 'admin/earnings/payout-lists',
    Earningtaskerlist: 'admin/earnings/tasker-lists',
    Payoutbillingcycle: 'admin/earnings/cycle-lists',
    Payoutfirstbillingcycle: 'admin/earnings/cycle-first',
    payouttakerearninglist: 'admin/earnings/tasker-earnings-list',
    Payoutupdatepayee: 'admin/earnings/update-payee',
    Payouttaskerpauot: 'admin/earnings/tasker-payout',
    documentstripe: 'admin/documents/stripe',
    exprotmangement: 'admin/download-csv-xlsv',

    taskeraddcategory: 'admin/taskers/savecategory',
    taskercategorydelete: 'admin/taskers/categorydelete',
    taskerapprovecat: 'admin/taskers/approvecategory',
    taskerbankinfo : 'admin/taskers/taskeraccountinfo',
    taskeradddocuments: 'admin/taskers/add-documents',
    taskerupdatedocuments : 'admin/taskers/update-documents',
    taskerdeletedocuments : 'admin/taskers/remove-documents',
    taskeruploaddocuments: 'site/users/tasker-image-upload',
    //SubAdmin
    subadminedit : 'admin/subadmin/edit',
    subadminlist : 'admin/subadmin/list',
    //forgot
    forgotpassword : 'admin/forgot-password',
    saveforgotpassword : 'admin/save-new-password',
    getpendingtaskerlist : 'admin/taskers/get-pending-tasker-list'
}


